### ISSUE TITLE
Injection issues

### ISSUE THREAD

**Issue by LLolloLLolo** [MatrixAura/Lepton-Client#2]
注入成功后 1.8.9客户端仍然是白端
debug: tools.jar found
client: Version 3.6
info: Waiting Minecraft process
info: Find a Minecraft process, PID: 9456
info: Attach to 9456
info: Detached successfully

**Comment by MatrixAura** [comment]
使用vanilla客户端

**Comment by LLolloLLolo** [comment]
是香草的

**Comment by MatrixAura** [comment]
主播抱歉我回复迟了，但这不是时空武器，你应该出示你的客户端log而不是注入器log，这样我不知道情况。我提出一些可能的情况：

1. 主播你用的不是1.8.9-vanilla客户端
2. 主播你客户端的java可能和注入器的java不兼容，考虑使用同一个java
3. 主播你可能注入过一次，或者重复注入导致的不兼容问题
4. 也可能有其他我不知道的情况
