### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by sniperrich** [MatrixAura/Lepton-Client#3]
![image](https://github.com/MatrixAura/Lepton-Client/assets/110087661/2f28e72b-9070-4efd-8996-cc606f02eabb)
gradle构建失败

**Comment by MatrixAura** [comment]
请下载Git，并确保网络稳定，或者将build.gradle的
`
buildConfig {
    buildConfigField "String", "HASH", "${execute("git rev-parse --short HEAD")}"
    buildConfigField "String", "BRANCH", "${execute("git branch").replace("* ", "")}"
    buildConfigField "String", "VERSION", "${project.version}"

    packageName "cn.matrixaura.lepton"
}`
替换为
`
buildConfig {
    buildConfigField "String", "HASH", "hash1"
    buildConfigField "String", "BRANCH", "branch1"
    buildConfigField "String", "VERSION", "${project.version}"

    packageName "cn.matrixaura.lepton"
}
`

**Comment by MatrixAura** [comment]
请下载Git，并确保网络稳定，或者将build.gradle的

```
buildConfig {
    buildConfigField "String", "HASH", "${execute("git rev-parse --short HEAD")}"
    buildConfigField "String", "BRANCH", "${execute("git branch").replace("* ", "")}"
    buildConfigField "String", "VERSION", "${project.version}"

    packageName "cn.matrixaura.lepton"
}
```
替换为
```
buildConfig {
    buildConfigField "String", "HASH", "hash1"
    buildConfigField "String", "BRANCH", "branch1"
    buildConfigField "String", "VERSION", "${project.version}"

    packageName "cn.matrixaura.lepton"
}
```

**Comment by MatrixAura** [comment]
其中`hash1` 和 `branch1` 可以随意替换
