### ISSUE TITLE
注入lunar发送的错误

### ISSUE THREAD

**Issue by sniperrich** [MatrixAura/Lepton-Client#4]
![image](https://github.com/MatrixAura/Lepton-Client/assets/110087661/4a2b004e-605a-4ccf-9792-73d01445d574)

**Comment by MatrixAura** [comment]
这是lunar的java问题，考虑使用lunar自身的java，当然也有可能是lunar的java关闭了attach功能，请考虑使用c++方式注入。
并且目前因为mapping问题与transformer不兼容，即使解决了java问题，暂时也无法注入lunar
